name: urbanheat
channels:
  - conda-forge

dependencies:
  - python=3.10
  - climada=6.1.0
  - numpy=1.26.4
  - pandas=2.1.4
  - scipy
  - xarray=2025.6.1
  - dask
  - bottleneck
  - cftime
  - numba
  - scikit-learn
  - netcdf4
  - h5py
  - tqdm
  - pyyaml
  - matplotlib
  - ipykernel
  - jupyterlab
  - rasterio=1.4.3
  - shapely
  - fiona=1.10.1
  - pyproj=3.7.1
  - geopandas=1.1.1
  - rioxarray
  - rtree
  - libspatialindex
  - osmnx
