name: urbanheat
channels:
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11

  - numpy
  - pandas
  - scipy
  - xarray
  - dask
  - bottleneck
  - cftime
  - numba
  - scikit-learn

  - netcdf4
  - h5py
  - tqdm
  - pyyaml

  - matplotlib
  - ipykernel
  - jupyterlab

  - gdal>=3.8,<3.9
  - rasterio>=1.3.9,<1.4
  - shapely>=2.0,<2.1
  - fiona>=1.9,<1.10
  - pyproj>=3.6,<3.7
  - geopandas>=0.14,<0.15
  - rioxarray
  - rtree            
  - libspatialindex

  # CLIMADA
  - climada          

  - pip
  - setuptools
  - pip:
     